### PR TITLE
fix encoding table for alphanumeric

### PR DESCRIPTION
**Pull request by mfalt**
Pretty sure this is the correct order

### CODE REVIEW

**Comment by johnnychen94** [comment]
Thanks for submitting this PR. This package was created by `@jiegillet` who is not using Julia anymore, which is why I asked him to move it to JuliaImages last winter. Revisiting and refreshing this package on top of JuliaImages ecosystem is planned as a part of the OSPP (GSoC-like) project. https://julialang.org/jsoc/gsoc/images/#better_qr_code_support_open_ended

There's a potential student on this project, I'll check this out with him by then.

**Comment by johnnychen94** [comment]
That said, if you are confident about the QR codes details and if you want to maintain and improve this package, I can send you an invitation.

**Comment by mfalt** [comment]
Hi, sorry about not being more informative in my PR, I assume that whoever was responsible for the repo would be able to easily verify it.
Thanks for taking care of the repo @johnnychen94! 
I noticed that the google lense app wasn't able to read the QRcodes generated here correctly. I found the same table as @jiegillet and changed the code accordingly, but I couldn't find a more authoritative source. However, the apps I tried works correctly with this fix so it should be fine to merge.

**Comment by johnnychen94** [comment]
I need to set up CI first before merging this PR; I'll see if I can manage to do it this weekend. I've added this PR to my todo-list but still feel free to ping me if I forget about it.

**Comment by johnnychen94** [comment]
I'll tag a new minor release for this and it will be very likely to be the last minor release.

In the future, we'll rename this package to QRCodes.jl to introduce the type `QRCode` for dispatch purposes (#8).
The QR decode is a part of the OSPP project and will be added here as well.

**Pull request merged**
